#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

\Nexion\Exception\ErrorHandler::register();

// Load environment variables
\Nexion\Config\Dotenv::load(__DIR__);

/** @var \Nexion\Foundation\Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(\Nexion\Console\Kernel::class);

$status = $kernel->handle(null);

exit($status);
